/**
 * Auto-tag generation based on video title keywords.
 * Used by the upload page to suggest tags and by backend for tag assignment.
 *
 * Uses regex patterns with word boundaries for accurate matching.
 */

interface TagRule {
  pattern: RegExp;
  tag: string;
}

const TAG_RULES: TagRule[] = [
  // gaming - game titles and gaming terms
  { pattern: /\brust\b/i, tag: "gaming" },
  { pattern: /\brusty\b/i, tag: "gaming" },
  { pattern: /\brustafied\b/i, tag: "gaming" },
  { pattern: /cs[\s-]*go/i, tag: "gaming" },
  { pattern: /\bcsgo\b/i, tag: "gaming" },
  { pattern: /\bfortnite\b/i, tag: "gaming" },
  { pattern: /\bh1z1\b/i, tag: "gaming" },
  { pattern: /\btarkov\b/i, tag: "gaming" },
  { pattern: /\beft\b/i, tag: "gaming" },
  { pattern: /\bvalheim\b/i, tag: "gaming" },
  { pattern: /\bpubg\b/i, tag: "gaming" },
  { pattern: /battle royale/i, tag: "gaming" },
  { pattern: /\bpvp\b/i, tag: "gaming" },
  { pattern: /soda dungeon/i, tag: "gaming" },
  { pattern: /creativerse/i, tag: "gaming" },
  { pattern: /supreme commander/i, tag: "gaming" },
  { pattern: /king of the kill/i, tag: "gaming" },
  { pattern: /oil rig/i, tag: "gaming" },
  { pattern: /solo survival/i, tag: "gaming" },
  { pattern: /live stream/i, tag: "gaming" },
  { pattern: /\bfps\b/i, tag: "gaming" },
  { pattern: /\besports\b/i, tag: "gaming" },
  { pattern: /\branked\b/i, tag: "gaming" },
  { pattern: /competitive/i, tag: "gaming" },
  { pattern: /minecraft/i, tag: "gaming" },
  { pattern: /warzone/i, tag: "gaming" },
  { pattern: /apex legends/i, tag: "gaming" },
  { pattern: /overwatch/i, tag: "gaming" },
  { pattern: /call of duty/i, tag: "gaming" },
  { pattern: /\bvalorant\b/i, tag: "gaming" },
  { pattern: /rocket league/i, tag: "gaming" },
  { pattern: /sea of thieves/i, tag: "gaming" },
  { pattern: /ark survival/i, tag: "gaming" },
  { pattern: /new world/i, tag: "gaming" },
  { pattern: /dead by daylight/i, tag: "gaming" },
  { pattern: /among us/i, tag: "gaming" },
  { pattern: /\bgta\b/i, tag: "gaming" },
  { pattern: /league of legends/i, tag: "gaming" },
  { pattern: /\bdota\b/i, tag: "gaming" },
  { pattern: /counter[\s-]*strike/i, tag: "gaming" },
  { pattern: /\broblox\b/i, tag: "gaming" },

  // game-dev - development tools and game creation
  { pattern: /\bunity\b/i, tag: "game-dev" },
  { pattern: /unreal engine/i, tag: "game-dev" },
  { pattern: /\bunet\b/i, tag: "game-dev" },
  { pattern: /\bue[45]\b/i, tag: "game-dev" },
  { pattern: /\bgodot\b/i, tag: "game-dev" },
  { pattern: /contingency/i, tag: "game-dev" },
  { pattern: /dedicated server/i, tag: "game-dev" },
  { pattern: /map making/i, tag: "game-dev" },
  { pattern: /\bmodding\b/i, tag: "game-dev" },
  { pattern: /car-building game/i, tag: "game-dev" },
  { pattern: /game\s*dev/i, tag: "game-dev" },
  { pattern: /level design/i, tag: "game-dev" },
  { pattern: /game engine/i, tag: "game-dev" },

  // crypto - mining and cryptocurrency
  { pattern: /\bnicehash\b/i, tag: "crypto" },
  { pattern: /\bbitcoin\b/i, tag: "crypto" },
  { pattern: /mining rig/i, tag: "crypto" },
  { pattern: /mining bitcoin/i, tag: "crypto" },
  { pattern: /\bhashrate\b/i, tag: "crypto" },
  { pattern: /gpu rig/i, tag: "crypto" },
  { pattern: /\bcrypto\b/i, tag: "crypto" },
  { pattern: /\bethereum\b/i, tag: "crypto" },
  { pattern: /\bnft\b/i, tag: "crypto" },
  { pattern: /\bblockchain\b/i, tag: "crypto" },

  // diy - building, fixing, vehicles, electronics
  { pattern: /\btrailer\b/i, tag: "diy" },
  { pattern: /\bsolar\b/i, tag: "diy" },
  { pattern: /wrap(ping)?\s*(a\s*)?(boat|pontoon)/i, tag: "diy" },
  { pattern: /shrinkwrap/i, tag: "diy" },
  { pattern: /\belectrical\b/i, tag: "diy" },
  { pattern: /\bwiring\b/i, tag: "diy" },
  { pattern: /\bfixing\b/i, tag: "diy" },
  { pattern: /\brepair\b/i, tag: "diy" },
  { pattern: /monster truck/i, tag: "diy" },
  { pattern: /\bwelding\b/i, tag: "diy" },
  { pattern: /\bgarage\b/i, tag: "diy" },
  { pattern: /\bmechanic\b/i, tag: "diy" },
  { pattern: /\bcamaro\b/i, tag: "diy" },
  { pattern: /\bdodge\b/i, tag: "diy" },
  { pattern: /car amp/i, tag: "diy" },
  { pattern: /\bgrowatt\b/i, tag: "diy" },
  { pattern: /\binvert(er|ed)\b/i, tag: "diy" },
  { pattern: /\bplow\b/i, tag: "diy" },
  { pattern: /ripping apart/i, tag: "diy" },
  { pattern: /woodwork/i, tag: "diy" },
  { pattern: /renovation/i, tag: "diy" },
  { pattern: /restore/i, tag: "diy" },
  { pattern: /\b3d print/i, tag: "diy" },
  { pattern: /power tools?/i, tag: "diy" },

  // cooking - food, recipes, baking
  { pattern: /\brecipe\b/i, tag: "cooking" },
  { pattern: /\bbaking\b/i, tag: "cooking" },
  { pattern: /\bwaffle/i, tag: "cooking" },
  { pattern: /\bpierogi/i, tag: "cooking" },
  { pattern: /\bsauce\b/i, tag: "cooking" },
  { pattern: /\bcooking\b/i, tag: "cooking" },
  { pattern: /\bnachos\b/i, tag: "cooking" },
  { pattern: /\bdinner\b/i, tag: "cooking" },
  { pattern: /\bhomemade\b/i, tag: "cooking" },
  { pattern: /\bingredient/i, tag: "cooking" },
  { pattern: /\bburger/i, tag: "cooking" },
  { pattern: /\blasagna\b/i, tag: "cooking" },
  { pattern: /\bbread\b/i, tag: "cooking" },
  { pattern: /\bcookies?\b/i, tag: "cooking" },
  { pattern: /sweet treat/i, tag: "cooking" },
  { pattern: /\byummy\b/i, tag: "cooking" },
  { pattern: /\bfood\b/i, tag: "cooking" },
  { pattern: /\bsoup\b/i, tag: "cooking" },
  { pattern: /\bskewer/i, tag: "cooking" },
  { pattern: /pork chop/i, tag: "cooking" },
  { pattern: /\bpie\b/i, tag: "cooking" },
  { pattern: /\boreo\b/i, tag: "cooking" },
  { pattern: /crunch wrap/i, tag: "cooking" },
  { pattern: /\bsalad\b/i, tag: "cooking" },
  { pattern: /\bmeal\b/i, tag: "cooking" },
  { pattern: /\bbaked\b/i, tag: "cooking" },
  { pattern: /\bloaf\b/i, tag: "cooking" },
  { pattern: /\bbuns?\b/i, tag: "cooking" },
  { pattern: /sandwich/i, tag: "cooking" },
  { pattern: /\bbeef\b/i, tag: "cooking" },
  { pattern: /\bveggie/i, tag: "cooking" },
  { pattern: /\bvegetable/i, tag: "cooking" },
  { pattern: /\bsteak\b/i, tag: "cooking" },
  { pattern: /\bchicken\b/i, tag: "cooking" },
  { pattern: /\bpasta\b/i, tag: "cooking" },
  { pattern: /\bpizza\b/i, tag: "cooking" },
  { pattern: /\bcake\b/i, tag: "cooking" },
  { pattern: /\bbbq\b/i, tag: "cooking" },
  { pattern: /\bgrill(ing|ed)?\b/i, tag: "cooking" },
  { pattern: /\bsmoke[dr]\b/i, tag: "cooking" },
  { pattern: /\bsmoking\b/i, tag: "cooking" },
  { pattern: /meal prep/i, tag: "cooking" },
  { pattern: /breakfast/i, tag: "cooking" },
  { pattern: /\blunch\b/i, tag: "cooking" },
  { pattern: /#easy(dinner|yummy)/i, tag: "cooking" },
  { pattern: /dinnerrecipes/i, tag: "cooking" },

  // lifestyle - family, personal, vlogs
  { pattern: /\bfamily\b/i, tag: "lifestyle" },
  { pattern: /\bfam\b/i, tag: "lifestyle" },
  { pattern: /\bkids?\b/i, tag: "lifestyle" },
  { pattern: /\bkiddos\b/i, tag: "lifestyle" },
  { pattern: /christmas/i, tag: "lifestyle" },
  { pattern: /\beaster\b/i, tag: "lifestyle" },
  { pattern: /halloween/i, tag: "lifestyle" },
  { pattern: /\bbirthday\b/i, tag: "lifestyle" },
  { pattern: /\bvlog\b/i, tag: "lifestyle" },
  { pattern: /memor(y|ies)/i, tag: "lifestyle" },
  { pattern: /\bhockey\b/i, tag: "lifestyle" },
  { pattern: /\bfyp\b/i, tag: "lifestyle" },
  { pattern: /\btiktok\b/i, tag: "lifestyle" },
  { pattern: /fam jam/i, tag: "lifestyle" },
  { pattern: /\bfriends?\b/i, tag: "lifestyle" },
  { pattern: /\bheart\b/i, tag: "lifestyle" },
  { pattern: /\bcough\b/i, tag: "lifestyle" },
  { pattern: /\btemu\b/i, tag: "lifestyle" },
  { pattern: /unboxing/i, tag: "lifestyle" },
  { pattern: /day in.*life/i, tag: "lifestyle" },
  { pattern: /routine/i, tag: "lifestyle" },
  { pattern: /haul/i, tag: "lifestyle" },
  { pattern: /review/i, tag: "lifestyle" },

  // outdoors - nature, outdoor activities
  { pattern: /\bfishing\b/i, tag: "outdoors" },
  { pattern: /\bsunset\b/i, tag: "outdoors" },
  { pattern: /\bsunrise\b/i, tag: "outdoors" },
  { pattern: /\bflower/i, tag: "outdoors" },
  { pattern: /\bgarden\b/i, tag: "outdoors" },
  { pattern: /\bhike\b/i, tag: "outdoors" },
  { pattern: /\bcamping\b/i, tag: "outdoors" },
  { pattern: /\bfirework/i, tag: "outdoors" },
  { pattern: /\bdrone\b/i, tag: "outdoors" },
  { pattern: /\baerial\b/i, tag: "outdoors" },
  { pattern: /\bforest\b/i, tag: "outdoors" },
  { pattern: /niagara/i, tag: "outdoors" },
  { pattern: /helicopter/i, tag: "outdoors" },
  { pattern: /\bbeach\b/i, tag: "outdoors" },
  { pattern: /\bmountain\b/i, tag: "outdoors" },
  { pattern: /\btrail\b/i, tag: "outdoors" },
  { pattern: /\bwaterfall\b/i, tag: "outdoors" },
  { pattern: /\bsnow\b/i, tag: "outdoors" },
  { pattern: /\bwinter\b/i, tag: "outdoors" },
  { pattern: /kayak/i, tag: "outdoors" },
  { pattern: /canoe/i, tag: "outdoors" },

  // crafts - handmade items
  { pattern: /\bbracelet/i, tag: "crafts" },
  { pattern: /\borigami\b/i, tag: "crafts" },
  { pattern: /\bbookmark/i, tag: "crafts" },
  { pattern: /\bcraft(s|ing)?\b/i, tag: "crafts" },
  { pattern: /\bcrochet/i, tag: "crafts" },
  { pattern: /\bknitting\b/i, tag: "crafts" },
  { pattern: /\bsewing\b/i, tag: "crafts" },
  { pattern: /\bembroidery\b/i, tag: "crafts" },
  { pattern: /\bscrapbook/i, tag: "crafts" },
  { pattern: /\bpottery\b/i, tag: "crafts" },
  { pattern: /\bresin\b/i, tag: "crafts" },
];

/**
 * Generate tags from a video title using regex pattern matching.
 * Returns deduplicated array of tag strings.
 */
export function generateTagsFromTitle(title: string): string[] {
  const tagSet = new Set<string>();

  for (const rule of TAG_RULES) {
    if (rule.pattern.test(title)) {
      tagSet.add(rule.tag);
    }
  }

  return Array.from(tagSet);
}
