import fs from 'fs';
import path from 'path';
import axios from 'axios';
import { v4 as uuidv4 } from 'uuid';
import { logger } from '../../core/logger.js';
import { getConfig } from '../../core/config.js';
import { dbRun } from '../../db/db.js';
import type { Order } from '../../types/index.js';

const MOD = 'producer:logo';

// ─── ComfyUI Flux.1-Schnell workflow template ─────────────────────────────────

function buildFluxWorkflow(prompt: string): Record<string, unknown> {
  return {
    '6': {
      inputs: {
        text: prompt,
        clip: ['30', 1],
      },
      class_type: 'CLIPTextEncode',
      _meta: { title: 'CLIP Text Encode (Positive Prompt)' },
    },
    '8': {
      inputs: {
        samples: ['31', 0],
        vae: ['30', 2],
      },
      class_type: 'VAEDecode',
      _meta: { title: 'VAE Decode' },
    },
    '9': {
      inputs: {
        filename_prefix: 'logo',
        images: ['8', 0],
      },
      class_type: 'SaveImage',
      _meta: { title: 'Save Image' },
    },
    '27': {
      inputs: {
        width: 1024,
        height: 1024,
        batch_size: 1,
      },
      class_type: 'EmptySD3LatentImage',
      _meta: { title: 'EmptySD3LatentImage' },
    },
    '30': {
      inputs: {
        ckpt_name: 'flux1-schnell-fp8.safetensors',
      },
      class_type: 'CheckpointLoaderSimple',
      _meta: { title: 'Load Checkpoint' },
    },
    '31': {
      inputs: {
        model: ['30', 0],
        conditioning: ['6', 0],
        latent_image: ['27', 0],
        seed: Math.floor(Math.random() * 2 ** 32),
        steps: 4,
        cfg: 1.0,
        sampler_name: 'euler',
        scheduler: 'simple',
        denoise: 1.0,
      },
      class_type: 'KSampler',
      _meta: { title: 'KSampler' },
    },
  };
}

// ─── Placeholder SVG fallback ─────────────────────────────────────────────────

function buildPlaceholderSvg(brief: string): string {
  const label = brief.slice(0, 40).replace(/[<>&"]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '&': '&amp;', '"': '&quot;' }[c] ?? c));
  return `<?xml version="1.0" encoding="UTF-8"?>
<svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient id="bg" x1="0%" y1="0%" x2="100%" y2="100%">
      <stop offset="0%" style="stop-color:#1a1a2e;stop-opacity:1" />
      <stop offset="100%" style="stop-color:#16213e;stop-opacity:1" />
    </linearGradient>
  </defs>
  <rect width="512" height="512" fill="url(#bg)" rx="24"/>
  <circle cx="256" cy="200" r="80" fill="none" stroke="#e94560" stroke-width="6"/>
  <polygon points="256,140 296,220 216,220" fill="#e94560" opacity="0.8"/>
  <text x="256" y="330" font-family="Arial, sans-serif" font-size="22" font-weight="bold"
        fill="#ffffff" text-anchor="middle" dominant-baseline="middle">LOGO PLACEHOLDER</text>
  <text x="256" y="365" font-family="Arial, sans-serif" font-size="13"
        fill="#aaaaaa" text-anchor="middle" dominant-baseline="middle">${label}</text>
  <text x="256" y="480" font-family="Arial, sans-serif" font-size="11"
        fill="#555555" text-anchor="middle">Generated by OperationUnderbid</text>
</svg>`;
}

// ─── ComfyUI helpers ──────────────────────────────────────────────────────────

interface ComfyHistoryOutput {
  images?: Array<{ filename: string; subfolder: string; type: string }>;
}

interface ComfyHistoryEntry {
  outputs: Record<string, ComfyHistoryOutput>;
  status: { completed: boolean; status_str: string };
}

async function pollUntilDone(
  comfyHost: string,
  promptId: string,
  timeoutMs = 300_000,
  intervalMs = 2_000,
): Promise<string> {
  const deadline = Date.now() + timeoutMs;

  while (Date.now() < deadline) {
    await new Promise((r) => setTimeout(r, intervalMs));

    const histRes = await axios.get<Record<string, ComfyHistoryEntry>>(
      `${comfyHost}/history/${promptId}`,
      { timeout: 10_000 },
    );

    const entry = histRes.data[promptId];
    if (!entry) continue;

    if (entry.status?.completed) {
      // Find the first output image filename
      for (const nodeOutput of Object.values(entry.outputs)) {
        if (nodeOutput.images && nodeOutput.images.length > 0) {
          return nodeOutput.images[0].filename;
        }
      }
      throw new Error(`ComfyUI job ${promptId} completed but no images found in output`);
    }

    if (entry.status?.status_str === 'error') {
      throw new Error(`ComfyUI job ${promptId} failed with status: error`);
    }
  }

  throw new Error(`ComfyUI job ${promptId} timed out after ${timeoutMs}ms`);
}

// ─── Main producer ────────────────────────────────────────────────────────────

export async function produceLogo(order: Order): Promise<string> {
  logger.info(MOD, `Starting logo production for order ${order.id}`, {
    buyer: order.buyer_name,
  });

  const deliverDir = path.resolve(process.cwd(), 'deliverables', order.id);
  try {
    fs.mkdirSync(deliverDir, { recursive: true });
  } catch (err) {
    throw new Error(`Failed to create deliverable directory ${deliverDir}: ${(err as Error).message}`);
  }

  const version = uuidv4();
  const cfg = getConfig();
  const comfyHost = cfg.comfyHost;

  // Craft a logo-focused image prompt from the brief
  const imagePrompt =
    `Professional logo design, clean vector style, white background, ${order.brief.slice(0, 300)}, ` +
    `high quality, sharp lines, minimalist, brand identity, no text watermarks`;

  let filePath: string;

  try {
    // ── Submit workflow to ComfyUI ──────────────────────────────────────────
    logger.info(MOD, `Submitting Flux.1-Schnell workflow to ComfyUI`, { comfyHost });

    const workflow = buildFluxWorkflow(imagePrompt);
    const submitRes = await axios.post<{ prompt_id: string }>(
      `${comfyHost}/prompt`,
      { prompt: workflow },
      { timeout: 15_000 },
    );

    const promptId = submitRes.data?.prompt_id;
    if (!promptId) {
      throw new Error(`ComfyUI did not return a prompt_id`);
    }

    logger.info(MOD, `ComfyUI job queued`, { promptId, orderId: order.id });

    // ── Poll until complete ─────────────────────────────────────────────────
    const filename = await pollUntilDone(comfyHost, promptId);
    logger.info(MOD, `ComfyUI job completed`, { promptId, filename });

    // ── Download image ──────────────────────────────────────────────────────
    const imageUrl = `${comfyHost}/view?filename=${encodeURIComponent(filename)}&type=output`;
    const imgRes = await axios.get<Buffer>(imageUrl, {
      responseType: 'arraybuffer',
      timeout: 30_000,
    });

    filePath = path.join(deliverDir, `logo-v${version}.png`);
    fs.writeFileSync(filePath, Buffer.from(imgRes.data));
    logger.info(MOD, `Logo PNG saved`, { filePath, orderId: order.id });

  } catch (err) {
    // ── Fallback: placeholder SVG ───────────────────────────────────────────
    const errMsg = (err as Error).message;
    logger.warn(MOD, `ComfyUI unavailable or failed — generating placeholder SVG`, {
      orderId: order.id,
      reason: errMsg,
    });

    filePath = path.join(deliverDir, `logo-v${version}.svg`);
    const svg = buildPlaceholderSvg(order.brief);
    try {
      fs.writeFileSync(filePath, svg, 'utf-8');
    } catch (writeErr) {
      throw new Error(`Failed to write placeholder SVG ${filePath}: ${(writeErr as Error).message}`);
    }
    logger.info(MOD, `Placeholder SVG saved`, { filePath, orderId: order.id });
  }

  // Persist deliverable record
  try {
    dbRun(
      `INSERT OR IGNORE INTO deliverables (id, order_id, file_path, file_type, version, is_final, created_at)
       VALUES (?, ?, ?, 'image', 1, 0, datetime('now'))`,
      [version, order.id, filePath],
    );
  } catch (err) {
    logger.warn(MOD, `DB insert failed for deliverable`, { orderId: order.id, err: (err as Error).message });
  }

  return filePath;
}
